server:
  servlet:
    context-path: /home
  error:
    whitelabel:
      enabled: false
    path: /error

spring:
  application:
            name: AOP
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
  datasource:
    url: jdbc:h2:./data/demo
    driver-class-name: org.h2.Driver
    username: admin
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: boot.demo.aop.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    sql: trace