-- 권한 등록
INSERT INTO PUBLIC.TB_ROLE (CODE, NAME) VALUES (1, 'USER');
INSERT INTO PUBLIC.TB_ROLE (CODE, NAME) VALUES (9, 'ADMIN');
INSERT INTO PUBLIC.TB_ROLE (CODE, NAME) VALUES (99, 'MASTER');

-- 테스트 사용자 등록
INSERT INTO PUBLIC.TB_USER_MST (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('admin', '$2a$10$.NM7PNXD6KsBYSNInpZTk.jQ.rlRmKKxmAMrOwysWVHv2gNpeFmN2', '관리자', null);
INSERT INTO PUBLIC.TB_USER_MST (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('test', '$2a$10$uYi7RIqUK9r1e8BlEvZptO8Jg9nETsb6aXuQnoSW0eeS.GH5.sW.K', '테스트 유저', null);
INSERT INTO PUBLIC.TB_USER_MST (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('master', '$2a$10$VN6oikhInhSIGK2w2m5vwe4P9SuMoQJi9A/FFz24uXmtTCsnHM7ke', '마스터 관리자', null);

-- 테스트 사용자 권한 등록
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 1);
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('admin', 9);
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('master', 1);
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('master', 9);
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('master', 99);
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('test', 1);
INSERT INTO PUBLIC.TB_USER_ROLE (USER_ID, ROLE_CODE) VALUES ('user', 1);

